# Stage 1: Získání Composeru z oficiálního Composer image
FROM composer:2.2 AS composer-stage

# Stage 2: Hlavní image s PHP 5.6
FROM php:5.6-fpm

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN apt-get update

# Instalace runtime závislostí: nginx, supervisor, curl
RUN apt-get install -y nginx supervisor curl

RUN install-php-extensions \
            intl \
            opcache \
            bcmath \
            mbstring \
            pdo \
            json \
            xml \
            soap \
            pcntl \
            gd \
            exif \
            pgsql pdo_pgsql \
            mysqli pdo_mysql \
            redis \
            zip


# Zkopírování Composeru z předchozí stage
COPY --from=composer-stage /usr/bin/composer /usr/bin/composer

# Kopírování konfigurace Supervisoru (soubor supervisord.conf musí být ve stejném adresáři)
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN mkdir -p /run/nginx

# Nastavení pracovního adresáře
WORKDIR /var/www/html

# Exponování portu 80
EXPOSE 80

CMD ["/usr/bin/supervisord", "-n"]
